class MALPEMDict:
    malpem_dict = {
        1: "3rdVentricle",
        2: "4thVentricle",
        3: "RightAccumbensArea",
        4: "LeftAccumbensArea",
        5: "RightAmygdala",
        6: "LeftAmygdala",
        7: "BrainStem",
        8: "RightCaudate",
        9: "LeftCaudate",
        10: "RightCerebellumExterior",
        11: "LeftCerebellumExterior",
        12: "RightCerebellumWhiteMatter",
        13: "LeftCerebellumWhiteMatter",
        14: "RightCerebralExterior",
        15: "LeftCerebralExterior",
        16: "RightCerebralWhiteMatter",
        17: "LeftCerebralWhiteMatter",
        18: "CSF",
        19: "RightHippocampus",
        20: "LeftHippocampus",
        21: "RightInfLatVent",
        22: "LeftInfLatVent",
        23: "RightLateralVentricle",
        24: "LeftLateralVentricle",
        25: "RightPallidum",
        26: "LeftPallidum",
        27: "RightPutamen",
        28: "LeftPutamen",
        29: "RightThalamusProper",
        30: "LeftThalamusProper",
        31: "RightVentralDC",
        32: "LeftVentralDC",
        33: "Rightvessel",
        34: "Leftvessel",
        35: "OpticChiasm",
        36: "CerebellarVermalLobulesI-V",
        37: "CerebellarVermalLobulesVI-VII",
        38: "CerebellarVermalLobulesVIII-X",
        39: "LeftBasalForebrain",
        40: "RightBasalForebrain",
        41: 'Ganteriorcingulategyrus Right',
        42: 'Ganteriorcingulategyrus Left',
        43: 'Anteriorinsula Right',
        44: 'Anteriorinsula Left',
        45: 'Anteriororbitalgyrus Right',
        46: 'Anteriororbitalgyrus Left',
        47: 'Angulargyrus Right',
        48: 'Angulargyrus Left',
        49: 'Calcarinecortex Right',
        50: 'Calcarinecortex Left',
        51: 'Centraloperculum Right',
        52: 'Centraloperculum Left',
        53: 'Cuneus Right',
        54: 'Cuneus Left',
        55: 'Ententorhinalarea Right',
        56: 'Ententorhinalarea Left',
        57: 'Frontaloperculum Right',
        58: 'Frontaloperculum Left',
        59: 'Frontalpole Right',
        60: 'Frontalpole Left',
        61: 'Fusiformgyrus Right',
        62: 'Fusiformgyrus Left',
        63: 'Gyrusrectus Right',
        64: 'Gyrusrectus Left',
        65: 'Inferioroccipitalgyrus Right',
        66: 'Inferioroccipitalgyrus Left',
        67: 'Inferiortemporalgyrus Right',
        68: 'Inferiortemporalgyrus Left',
        69: 'Lingualgyrus Right',
        70: 'Lingualgyrus Left',
        71: 'Lateralorbitalgyrus Right',
        72: 'Lateralorbitalgyrus Left',
        73: 'Middlecingulategyrus Right',
        74: 'Middlecingulategyrus Left',
        75: 'Medialfrontalcortex Right',
        76: 'Medialfrontalcortex Left',
        77: 'Middlefrontalgyrus Right',
        78: 'Middlefrontalgyrus Left',
        79: 'Middleoccipitalgyrus Right',
        80: 'Middleoccipitalgyrus Left',
        81: 'Medialorbitalgyrus Right',
        82: 'Medialorbitalgyrus Left',
        83: 'Postcentralgyrusmedialsegment Right',
        84: 'Postcentralgyrusmedialsegment Left',
        85: 'Precentralgyrusmedialsegment Right',
        86: 'Precentralgyrusmedialsegment Left',
        87: 'Superiorfrontalgyrusmedialsegment Right',
        88: 'Superiorfrontalgyrusmedialsegment Left',
        89: 'Middletemporalgyrus Right',
        90: 'Middletemporalgyrus Left',
        91: 'Occipitalpole Right',
        92: 'Occipitalpole Left',
        93: 'Occipitalfusiformgyrus Right',
        94: 'Occipitalfusiformgyrus Left',
        95: 'Opercularpartoftheinferiorfrontalgyrus Right',
        96: 'Opercularpartoftheinferiorfrontalgyrus Left',
        97: 'Orbitalpartoftheinferiorfrontalgyrus Right',
        98: 'Orbitalpartoftheinferiorfrontalgyrus Left',
        99: 'Posteriorcingulategyrus Right',
        100: 'Posteriorcingulategyrus Left',
        101: 'Precuneus Right',
        102: 'Precuneus Left',
        103: 'Parahippocampalgyrus Right',
        104: 'Parahippocampalgyrus Left',
        105: 'Posteriorinsula Right',
        106: 'Posteriorinsula Left',
        107: 'Parietaloperculum Right',
        108: 'Parietaloperculum Left',
        109: 'Postcentralgyrus Right',
        110: 'Postcentralgyrus Left',
        111: 'Posteriororbitalgyrus Right',
        112: 'Posteriororbitalgyrus Left',
        113: 'Planumpolare Right',
        114: 'Planumpolare Left',
        115: 'Precentralgyrus Right',
        116: 'Precentralgyrus Left',
        117: 'Planumtemporale Right',
        118: 'Planumtemporale Left',
        119: 'Subcallosalarea Right',
        120: 'Subcallosalarea Left',
        121: 'Superiorfrontalgyrus Right',
        122: 'Superiorfrontalgyrus Left',
        123: 'Supplementarymotorcortex Right',
        124: 'Supplementarymotorcortex Left',
        125: 'Supramarginalgyrus Right',
        126: 'Supramarginalgyrus Left',
        127: 'Superioroccipitalgyrus Right',
        128: 'Superioroccipitalgyrus Left',
        129: 'Superiorparietallobule Right',
        130: 'Superiorparietallobule Left',
        131: 'Superiortemporalgyrus Right',
        132: 'Superiortemporalgyrus Left',
        133: 'Temporalpole Right',
        134: 'Temporalpole Left',
        135: 'Triangularpartoftheinferiorfrontalgyrus Right',
        136: 'Triangularpartoftheinferiorfrontalgyrus Left',
        137: 'Transversetemporalgyrus Right',
        138: 'Transversetemporalgyrus Left'
    }

    def __init__(self):
        pass
