class TractSegDict:
    tractseg_dict = {
        0: "Arcuate fascicle left",
        1: "Arcuate fascicle right",
        2: "Anterior Thalamic Radiation left",
        3: "Anterior Thalamic Radiation right",
        4: "Commissure Anterior",
        5: "Rostrum of Corpus Callosum",
        6: "Genu of Corpus Callosum",
        7: "Rostral body of Corpus Callosum (Premotor)",
        8: "Anterior midbody of Corpus Callosum (Primary Motor)",
        9: "Posterior midbody of Corpus Callosum (Primary Somatosensory)",
        10: "Isthmus of Corpus Callosum",
        11: "Splenium of Corpus Callosum",
        12: "Cingulum left",
        13: "Cingulum right",
        14: "Corticospinal tract left",
        15: "Corticospinal tract right",
        16: "Middle longitudinal fascicle left",
        17: "Middle longitudinal fascicle right",
        18: "Fronto-pontine tract left",
        19: "Fronto-pontine tract right",
        20: "Fornix left",
        21: "Fornix right",
        22: "Inferior cerebellar peduncle left",
        23: "Inferior cerebellar peduncle right",
        24: "Inferior occipito-frontal fascicle left",
        25: "Inferior occipito-frontal fascicle right",
        26: "Inferior longitudinal fascicle left",
        27: "Inferior longitudinal fascicle right",
        28: "Middle cerebellar peduncle",
        29: "Optic radiation left",
        30: "Optic radiation right",
        31: "Parieto‐occipital pontine left",
        32: "Parieto‐occipital pontine right",
        33: "Superior cerebellar peduncle left",
        34: "Superior cerebellar peduncle right",
        35: "Superior longitudinal fascicle I left",
        36: "Superior longitudinal fascicle I right",
        37: "Superior longitudinal fascicle II left",
        38: "Superior longitudinal fascicle II right",
        39: "Superior longitudinal fascicle III left",
        40: "Superior longitudinal fascicle III right",
        41: "Superior Thalamic Radiation left",
        42: "Superior Thalamic Radiation right",
        43: "Uncinate fascicle left",
        44: "Uncinate fascicle right",
        45: "Corpus Callosum - all",
        46: "Thalamo-prefrontal left",
        47: "Thalamo-prefrontal right",
        48: "Thalamo-premotor left",
        49: "Thalamo-premotor right",
        50: "Thalamo-precentral left",
        51: "Thalamo-precentral right",
        52: "Thalamo-postcentral left",
        53: "Thalamo-postcentral right",
        54: "Thalamo-parietal left",
        55: "Thalamo-parietal right",
        56: "Thalamo-occipital left",
        57: "Temporal Occipital region right",
        58: "Striato-fronto-orbital region left",
        59: "Striato-fronto-orbital region right",
        60: "Striato-prefrontal region left",
        61: "Striato-prefrontal region right",
        62: "Striato-premotor region left",
        63: "Striato-premotor region right",
        64: "Striato-precentral region left",
        65: "Striato-precentral region right",
        66: "Striato-postcentral region left",
        67: "Striato-postcentral region right",
        68: "Striato-parietal region left",
        69: "Striato-parietal region right",
        70: "Striato-occipital region left",
        71: "Striato-occipital region right"
    }

    def __init__(self):
        pass




